# Generated by Django 3.0.14 on 2023-01-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lname',
            new_name='last_name',
        ),
    ]
